services:
  pipeline:
    build: pipeline
    ports:
      - 9011:9009
    environment:
      - POSTGRES_DB=example
      - SPARK_HOME=/usr/opt/pipeline/spark
    volumes:
      - ./pipeline/libs:/usr/opt/pipeline/libs
      - ./pipeline/cache:/usr/opt/pipeline/cache
      - ./pipeline/spark-2.4.8-bin-hadoop2.7:/usr/opt/pipeline/spark
      - /tmp/modou:/tmp/modou
    networks:
      - pipeline-network
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pipeline-network
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  pipeline-network:
